DockerFile: Updated Node PATH

diff --git a/.github/workflows/verify-image.yml b/.github/workflows/verify-image.yml
--- a/.github/workflows/verify-image.yml
+++ b/.github/workflows/verify-image.yml
@@ -20,5 +20,6 @@ jobs:
             echo '=== @cucumber/cucumber exists? ===' && (ls /usr/lib/node_modules/@cucumber/cucumber || ls /usr/local/lib/node_modules/@cucumber/cucumber || echo 'Not found ❌') &&
             echo '=== playwright-bdd exists? ===' && (ls /usr/lib/node_modules/playwright-bdd || ls /usr/local/lib/node_modules/playwright-bdd || echo 'Not found ❌') &&
             echo '=== playwright core ===' && (ls /usr/lib/node_modules/playwright || ls /usr/local/lib/node_modules/playwright || echo 'Not found ❌') &&
-            echo '=== find playwright ===' && find /usr -name 'playwright' -type d 2>/dev/null
+            echo '=== find playwright ===' && find /usr -name 'playwright' -type d 2>/dev/null &&
+            echo '=== playwright core ===' && ls /usr/lib/node_modules/@playwright/test/node_modules/playwright || echo 'Not found ❌'
           "
